services:
  nginx:
    container_name: "nginx"
    build:
      context: ./docker/nginx
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "${NGINX_FORWARD_PORT:-80}:80"
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - php
      - redis
      - postgresql
    networks:
      - laravel
    restart: unless-stopped

  postgresql:
    image: postgres:16.3
    container_name: "postgresql"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/postgres
      TZ: UTC
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${DB_DATABASE} -U ${DB_USERNAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgresql:/data/postgres
    ports:
      - "${DB_FORWARD_PORT:-5432}:5432"
    networks:
      - laravel
    restart: unless-stopped

  php:
    container_name: "php"
    build:
      context: ./docker/php
      dockerfile: php.dockerfile
      args:
        - NFDUMP_VERSION=${NFDUMP_VERSION:-1.7.4}
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "${PHP_FORWARD_PORT:-9000}:9000"
    volumes:
      - ./src:/var/www/html:delegated
      - ./docker/php/custom.php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./netflowData:/var/www/html/storage/app/netflowData
    networks:
      - laravel
    restart: unless-stopped

  redis:
    container_name: "redis"
    image: redis:alpine
    ports:
      - "${REDIS_FORWARD_PORT:-6379}:6379"
    volumes:
      - redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s
    networks:
      - laravel
    restart: unless-stopped

  nfdump:
    container_name: "nfdump"
    build:
      context: ./docker/nfdump
      dockerfile: nfdump.dockerfile
      args:
        - NFDUMP_VERSION=${NFDUMP_VERSION:-1.7.4}
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "${NFDUMP_FORWARD_PORT:-2055}:2055"
    volumes:
      - ./netflowData:/netflowData
    networks:
      - laravel
    restart: unless-stopped

  composer:
    container_name: "composer"
    build:
      context: ./docker/php
      dockerfile: php.dockerfile
      args:
        - NFDUMP_VERSION=${NFDUMP_VERSION:-1.7.4}
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php
    entrypoint: ["composer", "--ignore-platform-reqs"]
    networks:
      - laravel

  npm:
    container_name: "npm"
    image: node:current-alpine
    volumes:
      - ./src:/var/www/html
    ports:
      - "${NPM_FORWARD_PORT:-3000}:3000"
    working_dir: /var/www/html
    entrypoint: ["npm"]
    networks:
      - laravel

  artisan:
    container_name: "artisan"
    build:
      context: ./docker/php
      dockerfile: php.dockerfile
      args:
        - NFDUMP_VERSION=${NFDUMP_VERSION:-1.7.4}
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - postgresql
      - redis
    entrypoint: ["php", "/var/www/html/artisan"]
    networks:
      - laravel

volumes:
  postgresql:
    driver: local
  redis:
    driver: local

networks:
  laravel:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.68.0/24
